notifier: Don't ask for a lock forever
When the lock isn't acquired in reasonable amount of time, give up.

diff --git a/mail_notifier/notifier b/mail_notifier/notifier
--- a/mail_notifier/notifier
+++ b/mail_notifier/notifier
@@ -226,9 +226,16 @@ compose_message() {
 }
 
 lock() {
-	while ! mkdir "$1" >/dev/null 2>&1 ; do
-		sleep 1
+	# Try to acquire the lock. But only for a limited amount of time
+	# (15 minutes) to prevent too many waiting notifiers to gather in
+	# case something bad happens. It is started every 5 minutes anyway.
+	for i in `seq 1 900` ; do
+		if mkdir "$1" >/dev/null 2>&1 ; then
+			return
+		fi
 	done
+	echo "Failed to get the lock" >&2
+	exit 1
 }
 
 unlock() {
